// Package web implements the HTTP API server. Handlers are mounted under
// /api/* and read/write FS state through the storage and auth services.
//
// Auth model: cookie-based sessions (HttpOnly + SameSite=Lax + Secure when
// TLS is configured); CSRF protection via double-submit cookie + X-CSRF-Token
// header on mutating requests. See docs/arch/auth.md.
package web

import (
	"context"
	"errors"
	"net/http"
	"time"

	"github.com/alexnav/storman/internal/audit"
	"github.com/alexnav/storman/internal/auth"
	"github.com/alexnav/storman/internal/rbac"
	"github.com/alexnav/storman/internal/storage/dbfs"
)

// ReadyFunc is the readiness check used by /readyz. Returns nil when all
// backing dependencies (DB, etc.) are reachable, an error otherwise.
type ReadyFunc func(context.Context) error


const sessionCookieName = "storman_session"

// Config controls server-side cookie/security behavior. Mirrors fields from
// config.WebConfig so the web package stays decoupled from the on-disk format.
type Config struct {
	// SecureCookies is the operator preference (web.secure_cookies in config).
	// The actual Secure flag on each Set-Cookie is computed per-request via
	// secureForRequest — set to false here to never emit Secure (e.g., for
	// local dev over plain HTTP).
	SecureCookies bool
	// LocalTLS reports whether this server's own HTTP listener serves HTTPS.
	// When true, all requests are HTTPS regardless of proxy headers.
	LocalTLS bool
	// TrustProxyHeaders enables honouring X-Forwarded-Proto when deciding if
	// a request is HTTPS. Only safe when reachable only via a trusted reverse
	// proxy that strips client-supplied X-Forwarded-* headers.
	TrustProxyHeaders bool
	// LoginLimiter, if non-nil, is shared with other surfaces (FTPS) so an
	// attacker can't bypass the limit by switching protocols. When nil,
	// NewServer builds a private limiter with default settings.
	LoginLimiter *auth.LoginLimiter
	// Ready is the /readyz callback (typically a DB ping). Nil → /readyz
	// always returns 200.
	Ready ReadyFunc
	// MetricsHandler, if non-nil, is mounted at GET /metrics. Typically
	// produced by metrics.New().Handler() in serve.go.
	MetricsHandler http.Handler
}

// Server bundles the HTTP handler with its dependencies.
type Server struct {
	Config   Config
	Users    *auth.UserService
	Sessions *auth.SessionService
	Perms    *rbac.PermissionService
	Shares   *auth.ShareLinkService
	FS       *dbfs.DBFS
	Audit    *audit.Service
	// SPA, if non-nil, is mounted at /. It must implement the SPA-fallback
	// pattern itself (serve assets, fall back to index.html for unknown paths).
	SPA     http.Handler
	Handler http.Handler

	// loginLimiter rate-limits /api/auth/login (and WebDAV Basic auth) by
	// login name and client IP. Shared across surfaces when supplied via
	// Config.LoginLimiter — otherwise a private instance is built in NewServer.
	loginLimiter *auth.LoginLimiter

	// davAuth caches successful WebDAV Basic-auth results so macOS Finder's
	// per-request re-auth pattern doesn't drain the rate limiter or hammer
	// bcrypt. See webdav_authcache.go.
	davAuthCache *davAuthCache

	// setup holds the first-run setup token (generated by InitSetup when the
	// users table is empty, cleared once the first admin is created).
	setup setupState

	// davEnabled toggles the WebDAV interface mounted at davPrefix. Set via
	// SetDav; default off. Prefix is e.g. "/dav" — no trailing slash.
	davEnabled bool
	davPrefix  string
}

// NewServer wires the dependencies into an http.Handler. The returned Server's
// Handler is ready to be served by http.Server or net/http/httptest.
func NewServer(cfg Config, users *auth.UserService, sessions *auth.SessionService, perms *rbac.PermissionService, shares *auth.ShareLinkService, fs *dbfs.DBFS, auditSvc *audit.Service) *Server {
	limiter := cfg.LoginLimiter
	if limiter == nil {
		limiter = auth.NewLoginLimiter()
	}
	s := &Server{
		Config:       cfg,
		Users:        users,
		Sessions:     sessions,
		Perms:        perms,
		Shares:       shares,
		FS:           fs,
		Audit:        auditSvc,
		loginLimiter: limiter,
		davAuthCache: newDavAuthCache(60*time.Second, 1024),
	}
	s.Handler = s.routes()
	return s
}

// secureForRequest decides whether the Secure flag should be set on cookies
// emitted in response to r. Honours the SecureCookies preference (false → no
// Secure ever) and treats the request as HTTPS when either the local listener
// is TLS-terminated, or X-Forwarded-Proto=https arrives via a trusted proxy.
func (s *Server) secureForRequest(r *http.Request) bool {
	if !s.Config.SecureCookies {
		return false
	}
	if s.Config.LocalTLS {
		return true
	}
	if r != nil && s.Config.TrustProxyHeaders && r.Header.Get("X-Forwarded-Proto") == "https" {
		return true
	}
	return false
}

// audit is a nil-safe shortcut so handlers don't have to guard every call.
func (s *Server) audit(ctx context.Context, ev audit.Event) {
	if s.Audit == nil {
		return
	}
	s.Audit.Log(ctx, ev)
}

// WithSPA returns a new Server that serves the SPA from the given handler at
// root. Call before reading Handler.
func (s *Server) WithSPA(h http.Handler) *Server {
	s.SPA = h
	s.Handler = s.routes()
	return s
}

func (s *Server) routes() http.Handler {
	mux := http.NewServeMux()

	// Setup: open before the first admin exists, otherwise short-circuits to
	// 410. No CSRF (no session cookie yet); protection is the one-time token
	// printed to logs at startup.
	mux.Handle("GET /api/setup/state", s.chain(s.handleSetupState, openRoute))
	mux.Handle("POST /api/setup/admin", s.chain(s.handleSetupAdmin, openRoute))

	// Auth: login is open; logout and me require a session.
	mux.Handle("POST /api/auth/login", s.chain(s.handleLogin, openRoute))
	mux.Handle("POST /api/auth/logout", s.chain(s.handleLogout, authedMutate))
	mux.Handle("GET /api/auth/me", s.chain(s.handleMe, authedRead))

	// Filesystem.
	mux.Handle("GET /api/fs/stat", s.chain(s.handleStat, authedRead))
	mux.Handle("GET /api/fs/list", s.chain(s.handleList, authedRead))
	mux.Handle("POST /api/fs/mkdir", s.chain(s.handleMkdir, authedMutate))
	mux.Handle("DELETE /api/fs/remove", s.chain(s.handleRemove, authedMutate))
	mux.Handle("POST /api/fs/rename", s.chain(s.handleRename, authedMutate))
	mux.Handle("GET /api/fs/read", s.chain(s.handleRead, authedRead))
	mux.Handle("PUT /api/fs/write", s.chain(s.handleWrite, authedMutate))

	// Permissions + directory.
	mux.Handle("GET /api/users", s.chain(s.handleUsersList, authedRead))
	mux.Handle("POST /api/users", s.chain(s.handleUserCreate, authedMutate))
	mux.Handle("DELETE /api/users/{id}", s.chain(s.handleUserDelete, authedMutate))
	mux.Handle("POST /api/users/{id}/password", s.chain(s.handleUserPassword, authedMutate))
	mux.Handle("GET /api/perm/list", s.chain(s.handlePermList, authedRead))
	mux.Handle("POST /api/perm/grant", s.chain(s.handlePermGrant, authedMutate))
	mux.Handle("POST /api/perm/revoke", s.chain(s.handlePermRevoke, authedMutate))

	// Trash (admin-only — see trash.go for visibility rationale).
	mux.Handle("GET /api/trash", s.chain(s.handleTrashList, authedRead))
	mux.Handle("POST /api/trash/{id}/restore", s.chain(s.handleTrashRestore, authedMutate))
	mux.Handle("DELETE /api/trash/{id}", s.chain(s.handleTrashPurge, authedMutate))

	// Audit (admin-only).
	mux.Handle("GET /api/audit", s.chain(s.handleAuditList, authedRead))

	// Liveness/readiness/metrics — unauthenticated by design so probes and
	// scrapers work without credentials. Lock down via the network layer if
	// the listener is exposed to untrusted clients.
	mux.HandleFunc("GET /healthz", s.handleHealthz)
	mux.HandleFunc("GET /readyz", s.handleReadyz)
	if s.Config.MetricsHandler != nil {
		mux.Handle("GET /metrics", s.Config.MetricsHandler)
	}

	// tus.io resumable uploads (docs/arch/interfaces.md). authedRead semantics for HEAD/
	// OPTIONS (idempotent), authedMutate for POST/PATCH/DELETE — but tus
	// clients don't speak CSRF, so all tus routes run through authedRead.
	// Auth is still enforced via session middleware.
	mux.Handle("OPTIONS /api/tus", s.chain(s.handleTusOptions, authedRead))
	mux.Handle("POST /api/tus", s.chain(s.handleTusCreate, authedRead))
	mux.Handle("HEAD /api/tus/{id}", s.chain(s.handleTusHead, authedRead))
	mux.Handle("PATCH /api/tus/{id}", s.chain(s.handleTusPatch, authedRead))
	mux.Handle("DELETE /api/tus/{id}", s.chain(s.handleTusDelete, authedRead))

	// Share-links: authenticated CRUD + anonymous use under /share/{token}.
	mux.Handle("POST /api/share", s.chain(s.handleShareCreate, authedMutate))
	mux.Handle("GET /api/share/mine", s.chain(s.handleShareListMine, authedRead))
	mux.Handle("GET /api/share/all", s.chain(s.handleShareListAll, authedRead))
	mux.Handle("DELETE /api/share/{token}", s.chain(s.handleShareRevoke, authedMutate))
	mux.Handle("GET /share/{token}/info", s.chain(s.handleShareInfo, openRoute))
	mux.Handle("GET /share/{token}/download", s.chain(s.handleShareDownload, openRoute))
	mux.Handle("PUT /share/{token}/upload", s.chain(s.handleShareUpload, openRoute))

	// WebDAV — mounted as a path-prefix pattern so all methods (PROPFIND,
	// MKCOL, COPY, MOVE, LOCK, …) route through one handler. Must register
	// before the SPA catch-all so /dav/* doesn't fall through to it.
	if s.davEnabled {
		mux.Handle(s.davPrefix+"/", s.davHandler())
	}

	// SPA static + index fallback for any non-/api route. Registered without
	// a method so it doesn't collide with method-less prefix patterns like
	// "/dav/" (Go's ServeMux rejects a GET-/ vs /dav/ pair as ambiguous: one
	// is more specific on method, the other on path). The SPA handler itself
	// rejects non-GET/HEAD with 405.
	if s.SPA != nil {
		mux.Handle("/", s.SPA)
	}

	return securityHeaders(mux)
}

// chain composes a handler with the configured middleware bundle.
func (s *Server) chain(h http.HandlerFunc, kind routeKind) http.Handler {
	var wrapped http.Handler = h
	wrapped = s.recoverMiddleware(wrapped)
	if kind != openRoute {
		wrapped = s.sessionMiddleware(wrapped)
	}
	if kind == authedMutate {
		wrapped = s.csrfMiddleware(wrapped)
	}
	return wrapped
}

type routeKind int

const (
	openRoute    routeKind = iota // no session required (login)
	authedRead                    // session required, no CSRF
	authedMutate                  // session required, CSRF required
)

// sessionMiddleware reads the session cookie, validates the session, and
// stashes the user record in the request context. Unauthenticated requests
// are rejected with 401.
func (s *Server) sessionMiddleware(next http.Handler) http.Handler {
	return http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		cookie, err := r.Cookie(sessionCookieName)
		if err != nil || cookie.Value == "" {
			writeError(w, r, auth.ErrSessionExpired)
			return
		}
		sess, err := s.Sessions.Validate(r.Context(), cookie.Value)
		if err != nil {
			// Any session-validation failure collapses to "please log in"
			// (401) instead of 404 / 500 — keeps the auth boundary clean.
			if errors.Is(err, auth.ErrNotFound) || errors.Is(err, auth.ErrSessionExpired) {
				writeError(w, r, auth.ErrSessionExpired)
				return
			}
			writeError(w, r, err)
			return
		}
		user, err := s.Users.FindByID(r.Context(), sess.UserID)
		if err != nil {
			if errors.Is(err, auth.ErrNotFound) {
				writeError(w, r, auth.ErrSessionExpired)
				return
			}
			writeError(w, r, err)
			return
		}
		ctx := context.WithValue(r.Context(), ctxKeyUser{}, &user)
		// Best-effort sliding refresh — errors here aren't fatal to the request.
		_ = s.Sessions.Touch(ctx, sess.ID)
		next.ServeHTTP(w, r.WithContext(ctx))
	})
}

// csrfMiddleware enforces the double-submit cookie pattern for mutating
// requests: the CSRF cookie value must match the X-CSRF-Token header.
func (s *Server) csrfMiddleware(next http.Handler) http.Handler {
	return http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		cookie, err := r.Cookie(csrfCookieName)
		if err != nil {
			writeJSON(w, http.StatusForbidden, errorBody{Error: "csrf cookie missing"})
			return
		}
		if !csrfMatches(cookie.Value, r.Header.Get(csrfHeaderName)) {
			writeJSON(w, http.StatusForbidden, errorBody{Error: "csrf token mismatch"})
			return
		}
		next.ServeHTTP(w, r)
	})
}

// recoverMiddleware turns panics into 500s. Without it, a handler bug would
// kill the entire process.
func (s *Server) recoverMiddleware(next http.Handler) http.Handler {
	return http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		defer func() {
			if rv := recover(); rv != nil {
				writeError(w, r, errors.New("panic in handler"))
			}
		}()
		next.ServeHTTP(w, r)
	})
}

// securityHeaders sets defensive response headers on every response. See
// docs/arch/auth.md.
func securityHeaders(next http.Handler) http.Handler {
	return http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		h := w.Header()
		h.Set("X-Frame-Options", "DENY")
		h.Set("Referrer-Policy", "same-origin")
		h.Set("Content-Security-Policy", "default-src 'self'")
		h.Set("Strict-Transport-Security", "max-age=31536000; includeSubDomains")
		next.ServeHTTP(w, r)
	})
}

// ctxKeyUser is the context key for the authenticated user (set by
// sessionMiddleware, read by handlers).
type ctxKeyUser struct{}

// UserFromContext returns the authenticated user attached by the session
// middleware, or nil if the request is not authenticated (which should only
// happen on openRoute endpoints).
func UserFromContext(ctx context.Context) *auth.User {
	u, _ := ctx.Value(ctxKeyUser{}).(*auth.User)
	return u
}
