package auth

import (
	"context"
	"errors"
	"fmt"
	"time"

	"github.com/google/uuid"
	"github.com/jackc/pgx/v5"
)

// AuthenticateFTP verifies login + secret against either the main password or
// any of the user's app_passwords. App passwords exist so 2FA-protected
// accounts can still hand a long-lived secret to FTP clients that don't
// support TOTP — see PLAN §3.3. Calls the same brute-force counters as the
// main login so an attacker can't burn through credentials over FTP.
//
// Returns the same error palette as Authenticate.
func (s *UserService) AuthenticateFTP(ctx context.Context, login, secret string) (User, error) {
	// First try the main password — same code path as web login.
	user, err := s.Authenticate(ctx, login, secret)
	if err == nil {
		return user, nil
	}
	// Don't fall through on lockout: app-password attempts must respect the
	// same cooldown so brute-force across both surfaces is bounded.
	if errors.Is(err, ErrAccountLocked) || errors.Is(err, ErrNotFound) {
		return User{}, err
	}
	if !errors.Is(err, ErrPasswordMismatch) {
		return User{}, err
	}

	// Main password mismatched — try app passwords.
	u, lookupErr := s.FindByLogin(ctx, login)
	if lookupErr != nil {
		// Mirror the original error to avoid leaking login validity.
		return User{}, err
	}

	rows, err2 := s.pool.Query(ctx,
		`SELECT id, hash FROM app_passwords WHERE user_id = $1`, u.ID)
	if err2 != nil {
		return User{}, fmt.Errorf("load app passwords: %w", err2)
	}
	defer rows.Close()
	for rows.Next() {
		var tokenID uuid.UUID
		var hash string
		if err := rows.Scan(&tokenID, &hash); err != nil {
			return User{}, err
		}
		if VerifyPassword(secret, hash) == nil {
			// Match — record last_used and return the user. Don't bump
			// failed_attempts again (we already did inside Authenticate).
			if _, err := s.pool.Exec(ctx,
				`UPDATE app_passwords SET last_used = $1 WHERE id = $2`,
				time.Now().UTC(), tokenID); err != nil {
				return User{}, fmt.Errorf("update last_used: %w", err)
			}
			if _, err := s.pool.Exec(ctx,
				`UPDATE users SET failed_attempts = 0, locked_until = NULL WHERE id = $1`,
				u.ID); err != nil {
				return User{}, fmt.Errorf("reset counters: %w", err)
			}
			return u, nil
		}
	}
	if err := rows.Err(); err != nil {
		return User{}, err
	}
	// No match anywhere — propagate the original mismatch.
	return User{}, err
}

// CreateAppPassword issues a new long-lived secret for the given user. The
// raw token is generated by the caller (so it can be displayed once); only
// the argon2id hash is persisted.
func (s *UserService) CreateAppPassword(ctx context.Context, userID uuid.UUID, label, token string) (uuid.UUID, error) {
	hash, err := HashPassword(token, s.params)
	if err != nil {
		return uuid.Nil, err
	}
	id := uuid.New()
	_, err = s.pool.Exec(ctx,
		`INSERT INTO app_passwords (id, user_id, label, hash) VALUES ($1, $2, $3, $4)`,
		id, userID, label, hash)
	if err != nil {
		return uuid.Nil, fmt.Errorf("insert app password: %w", err)
	}
	return id, nil
}

// ListAppPasswords returns the (id, label, created_at, last_used) for each
// app password belonging to userID.
func (s *UserService) ListAppPasswords(ctx context.Context, userID uuid.UUID) ([]AppPassword, error) {
	rows, err := s.pool.Query(ctx,
		`SELECT id, label, created_at, last_used FROM app_passwords WHERE user_id = $1 ORDER BY created_at`,
		userID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	out := make([]AppPassword, 0)
	for rows.Next() {
		var p AppPassword
		if err := rows.Scan(&p.ID, &p.Label, &p.CreatedAt, &p.LastUsed); err != nil {
			return nil, err
		}
		out = append(out, p)
	}
	return out, rows.Err()
}

// DeleteAppPassword revokes a single token.
func (s *UserService) DeleteAppPassword(ctx context.Context, id uuid.UUID) error {
	tag, err := s.pool.Exec(ctx, `DELETE FROM app_passwords WHERE id = $1`, id)
	if err != nil {
		return err
	}
	if tag.RowsAffected() == 0 {
		return ErrNotFound
	}
	return nil
}

// AppPassword is the user-visible projection of one app_passwords row.
type AppPassword struct {
	ID        uuid.UUID
	Label     string
	CreatedAt time.Time
	LastUsed  *time.Time
}

// ensure pgx import isn't dropped if the file shrinks.
var _ = pgx.ErrNoRows
